language: node_js
services: mongodb
before_script:
  - cd server/
  - npm install
node_js:
  - "0.10"
branches:
  only:
    - master
    - fix-travis-build
notifications:
  email:
    - andrea.rossi@unep-wcmc.org
